[package]
name = "hanshi-mermaid"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
merman = { version = "=0.7.0", default-features = false, features = ["render"] }
resvg = { version = "=0.47.0", default-features = false, features = ["text", "system-fonts", "memmap-fonts"] }

[profile.release]
lto = "thin"
codegen-units = 1
panic = "unwind"
